<?php $this->layout('layout', ["title" => $current->getName()]) ?>

<div class="wrapper">
    <div id="sidebar" class="sidebar_scroll"> 
        <div class="scroll_container">
            <a class="logo" href="<?php echo $this->url("home"); ?>"><img src="<?php echo $this->baseUrl("/public/images/Logo_path.svg") ?>" /></a>
            <a id="menu_toggle" onclick="$('#menu').toggleClass('menu_show')"><i class="fa fa-bars" aria-hidden="true"></i> Menu</a>
            <ul id="menu" class="m">
                <?php foreach ($root->getChildren()[1]->getChildren() as $node){?>
                    <li class="m-header">
                        <?= $node->getName() ?>
                    </li>
                    <?php foreach ($node->getChildren() as $c_node){ ?>
                        <li class="m-item <?= ($c_node->isActive($current) ? "active" :"") ?>">
                            <a href="<?= $this->url(["name" => "md", "params" => ["path" => $c_node->getUrl()]]) ?>">
                                <?= $c_node->getName() ?>
                            </a>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>       
    </div>
    <div class="content">
        <div class="content_white clearfix">
            <?= $md->parseMD($current->getContent()) ?>
        </div>

        <div class="footer-space"></div>
    </div>
</div>
