
<?php $this->layout('layout', ["title" => $current->getDisplayName()]) ?>

<main class="doc">

	<a href="<?php echo $this->url("home") ?>">
		<img class="hubert" src="<?php echo $this->baseUrl("/public/images/hubert.png") ?>" alt="Hubert"/>
	</a>
	<br>

	<section class="menu">
		<ul>

			<?php foreach ($root->getChildren()[0]->getChildren() as $node) { ?>

				<li>
					<h3><?= $node->getDisplayName() ?></h3>
				</li>

				<?php foreach ($node->getChildren() as $c_node) { ?>

					<li class="<?= ($c_node->isActive($current) ? "active" : "") ?>">
						<a href="<?= $this->url("doc", ["language" => $language, "path" => $c_node->getUrlPath()]) ?>">
							<?= $c_node->getDisplayName() ?>
						</a>
					</li>

				<?php } ?>

			<?php } ?>

		</ul>
	</section>

	<section class="content">
		<?= $current->getContent() ?>
	</section>

</main>
