
<?php $this->layout('layout', ["title" => $current->getDisplayName()]) ?>

<main class="doc">

	<a href="<?php echo $this->url("home") ?>">
		<img class="hubert" src="<?php echo $this->baseUrl("/public/images/hubert.png") ?>" alt="Hubert"/>
	</a>
	<br>

	<span class="toggle" onclick="$('.menu').toggleClass('active')"><i class="fa fa-list"></i><i class="fa fa-caret-down"></i></span>
	<section class="menu">
		<ul>

			<?php foreach ($root->getChildren()[0]->getChildren() as $node) { ?>

				<li>
					<h3><?= $node->getDisplayName() ?></h3>
					<ul>

						<?php foreach ($node->getChildren() as $c_node) { ?>

							<li class="<?= ($c_node->isActive($current) ? "active" : "") ?>">
								<a href="<?= $this->url("doc", ["language" => $language, "path" => $c_node->getUrlPath()]) ?>">
									<?= $c_node->getDisplayName() ?>
								</a>
							</li>

						<?php } ?>

					</ul>
				</li>

			<?php } ?>

		</ul>
	</section>

	<section class="content">
		<?= $current->getContent() ?>
	</section>

</main>
