<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
    <meta name="format-detection" content="telephone=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?=$this->e((isset($title) ? $title : "Hubert"))?></title>
    <meta name="description" content="Hubert is a PHP micro framework that's fast, easy to use and easy to extend."/>
    
    <link href="<?= $this->baseUrl("/public/styles.min.css") ?>" rel="stylesheet">
    <?=$this->section('head')?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   
    <?=$this->section('content')?>

    <footer>
        <section>
	        <ul>
		        <li><a href="<?php echo $this->url("doc", ["language" => "en", "path" => "documentation"]) ?>"><? echo $translate["doc"] ?></a></li>
		        <li><a href="https://falk-m.de/impressum/" target="_blank"><? echo $translate["imp"] ?></a></li>
		        <li><a href="<?php echo $this->url("home_language", ["language" => "$translate[slug]"]) ?>"><? echo $translate["wording"] ?></a></li>
	        </ul>
        </section>
        <section>
                made with <i class="fa fa-heart"></i> in leipzig<br/>
        </section>
    </footer>
      
    <script src="<?= $this->baseUrl("/public/scripts/jquery-3.1.0.min.js") ?>"></script>
     <?=$this->section('scripts')?>

  </body>
</html>